version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpwd
      POSTGRES_DB: coinche
    ports:
      - 5432:5432
  admin:
    image: adminer
    ports:
      - 99:8080

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@pg.pg
      PGADMIN_DEFAULT_PASSWORD: pw
    ports:
      - 100:80
