"""Added game table

Revision ID: 340a14717a87
Revises: 
Create Date: 2023-05-29 12:39:56.338414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340a14717a87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('creator', sa.Integer(), nullable=False),
    sa.Column('player_a1', sa.Integer(), nullable=False),
    sa.Column('player_a2', sa.Integer(), nullable=False),
    sa.Column('player_b1', sa.Integer(), nullable=False),
    sa.Column('player_b2', sa.Integer(), nullable=False),
    sa.Column('score_a', sa.Integer(), nullable=False),
    sa.Column('score_b', sa.Integer(), nullable=False),
    sa.Column('stars_a', sa.Integer(), nullable=False),
    sa.Column('stars_b', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
