"""Add nullable false

Revision ID: 68ff914fa880
Revises: aa117a1cda37
Create Date: 2023-06-07 16:32:02.364864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ff914fa880'
down_revision = 'aa117a1cda37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'player_a1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'player_a1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
