"""Add slug column

Revision ID: 7e5f95044242
Revises: f81a22ba4458
Create Date: 2023-06-06 14:58:19.773957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5f95044242'
down_revision = 'f81a22ba4458'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('slug_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['slug_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'slug_name')
    # ### end Alembic commands ###
