"""Nested user object

Revision ID: aa117a1cda37
Revises: 061d3a1a1328
Create Date: 2023-06-07 16:22:41.279315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa117a1cda37'
down_revision = '061d3a1a1328'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('player_a1_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('player_a2_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('player_b1_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('player_b2_id', sa.Integer(), nullable=True))
    op.drop_constraint('games_player_a2_fkey', 'games', type_='foreignkey')
    op.drop_constraint('games_player_b1_fkey', 'games', type_='foreignkey')
    op.drop_constraint('games_player_b2_fkey', 'games', type_='foreignkey')
    op.drop_constraint('games_player_a1_fkey', 'games', type_='foreignkey')
    op.create_foreign_key(None, 'games', 'users', ['player_b1_id'], ['id'])
    op.create_foreign_key(None, 'games', 'users', ['player_b2_id'], ['id'])
    op.create_foreign_key(None, 'games', 'users', ['player_a1_id'], ['id'])
    op.create_foreign_key(None, 'games', 'users', ['player_a2_id'], ['id'])
    op.drop_column('games', 'player_b1')
    op.drop_column('games', 'player_a2')
    op.drop_column('games', 'player_b2')
    op.drop_column('games', 'player_a1')
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('games', sa.Column('player_a1', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('player_b2', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('player_a2', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('player_b1', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_foreign_key('games_player_a1_fkey', 'games', 'users', ['player_a1'], ['id'])
    op.create_foreign_key('games_player_b2_fkey', 'games', 'users', ['player_b2'], ['id'])
    op.create_foreign_key('games_player_b1_fkey', 'games', 'users', ['player_b1'], ['id'])
    op.create_foreign_key('games_player_a2_fkey', 'games', 'users', ['player_a2'], ['id'])
    op.drop_column('games', 'player_b2_id')
    op.drop_column('games', 'player_b1_id')
    op.drop_column('games', 'player_a2_id')
    op.drop_column('games', 'player_a1_id')
    # ### end Alembic commands ###
