"""Modify game table

Revision ID: f81a22ba4458
Revises: 66d65ae8a836
Create Date: 2023-05-30 16:47:55.553237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = 'f81a22ba4458'
down_revision = '66d65ae8a836'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.get_bind().execute(text("delete from games"))
    op.add_column('games', sa.Column('a_won', sa.Boolean(), nullable=False))
    op.add_column('games', sa.Column('b_won', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'games', 'users', ['creator'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'b_won')
    op.drop_column('games', 'a_won')
    # ### end Alembic commands ###
